// One call per page for everything that describes it to something other than a
// browser viewport: title, description, canonical, Open Graph, Twitter card.
// Not used on /pitch/<slug> — those are unlisted by design and stay noindex.
type PageSeo = {
  title: string // lowercase, per the Lowercase Rule; the site name is appended for og/twitter
  description: string
  image?: string // absolute path under /og, generated by scripts/og.mjs
  bare?: boolean // home page only: it *is* the site name, so don't append it
}

const SITE_NAME = 'dominik reisach'

export function usePageSeo({ title, description, image = '/og/default.jpg', bare }: PageSeo) {
  const site = useRuntimeConfig().public.site
  const path = useRoute().path
  // GitHub Pages 301s /about -> /about/, so emit the form it actually serves,
  // matching the sitemap in nuxt.config.ts
  const url = site + (path.endsWith('/') ? path : `${path}/`)
  const full = bare ? title : `${title} · ${SITE_NAME}`

  useHead({
    title,
    ...(bare && { titleTemplate: null }),
    link: [{ rel: 'canonical', href: url }],
  })

  useSeoMeta({
    description,
    ogType: 'website',
    ogSiteName: SITE_NAME,
    ogTitle: full,
    ogDescription: description,
    ogUrl: url,
    ogImage: site + image,
    ogImageWidth: 1200,
    ogImageHeight: 630,
    ogImageAlt: full,
    twitterCard: 'summary_large_image',
    twitterTitle: full,
    twitterDescription: description,
    twitterImage: site + image,
  })
}
