// Emits app/utils/mediaSize.ts — the intrinsic pixel size of every gallery image,
// keyed by the extensionless basename that frontmatter already uses as `src`.
// Purely an aspect-ratio hint for <img width/height>, so the browser reserves the
// right box before the file decodes; Tailwind preflight's `height: auto` keeps CSS
// in charge of the rendered size. Dimensions live here rather than in frontmatter
// because they are a property of the file on disk, not of the content.
// Rerun after adding or re-encoding imagery: `node scripts/media-size.mjs`
import { execFileSync } from 'node:child_process'
import { readdirSync, writeFileSync } from 'node:fs'

const OUT = 'app/utils/mediaSize.ts'

// the .jpg twin is authoritative: it is what a width/height-less <img> actually loads,
// and the .avif is encoded from it at the same dimensions
const files = readdirSync('public/imgs', { recursive: true })
  .filter(f => f.endsWith('.jpg'))
  .map(f => `public/imgs/${f}`)
  .sort()

// one sips call for all of them; it prints a path line then the two properties
const out = execFileSync('sips', ['-g', 'pixelWidth', '-g', 'pixelHeight', ...files], {
  encoding: 'utf8',
  maxBuffer: 1 << 24,
})

const sizes = []
for (const block of out.split(/^(?=\/)/m)) {
  const key = block.match(/\/imgs\/.*?(?=\.jpg)/)?.[0]
  const w = block.match(/pixelWidth: (\d+)/)?.[1]
  const h = block.match(/pixelHeight: (\d+)/)?.[1]
  if (key && w && h) sizes.push([key, +w, +h])
}

if (sizes.length !== files.length)
  throw new Error(`sips returned ${sizes.length} sizes for ${files.length} files`)

writeFileSync(
  OUT,
  `// GENERATED by scripts/media-size.mjs — do not edit by hand.
// Intrinsic pixel dimensions per media basename, for <img width/height> CLS reservation.
export const mediaSize: Record<string, [number, number]> = {
${sizes.map(([k, w, h]) => `  "${k}": [${w}, ${h}],`).join('\n')}
};

// Absent entries fall back to undefined, which renders no attribute at all —
// the pre-2026 behaviour, so a newly added image degrades rather than breaks.
export const sizeAttrs = (src: string) => {
  const [width, height] = mediaSize[src.replace(/\\.(jpg|avif)$/, "")] ?? [];
  return { width, height };
};
`,
)
console.log(`${OUT}: ${sizes.length} entries`)
